version: "3.9"

services:
  log-monitor:
    build:
      context: .
      dockerfile: dockerfile
    container_name: log-watcher
    restart: always

  log-generator:
    build:
      context: .
      dockerfile: dockerfile.generator
    container_name: log-writer
    restart: always

