FROM jenkins/jenkins:lts

USER root

# Install Docker CLI
RUN apt-get update && apt-get install -y \
    docker.io \
    docker-compose \
    git \
    curl \
    sudo

# Let the jenkins user use docker without sudo
RUN usermod -aG docker jenkins
    

# Allow Jenkins to run Docker

USER jenkins

