version: "3.9"

services:
  log-monitor:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: log-watcher
    volumes:
      - ./sample.log:/app/sample.log
    restart: always

  log-generator:
    build:
      context: .
      dockerfile: dockerfile.generator
    container_name: log-writer
    volumes:
      - ./sample.log:/app/sample.log
    restart: always

  #jenkins:
   # image: jenkins/jenkins:lts
    #container_name: jenkins
    #user: root
    #ports:
     # - "8081:8080"
      #- "50000:50000"
    #volumes:
     # - ./jenkins_home:/var/jenkins_home
      #- /var/run/docker.sock:/var/run/docker.sock
    #restart: unless-stopped

