name: CI Pipeline

on:
  push:
    branches: [ Test ]
  pull_request:
    branches: [ Test ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: pytest
      
    - name: Run Test with coverage
      run: |
           pip install pytest-cov
           pytest -cov=. --cov-report=term-missing

  docker-build:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image
      run: |
        docker compose version
        docker compose build
        
