name: Build and Push to GHCR

on:
  push:
    branches: [ main ]  # or change to your branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    #- name: Build and Push images with Compose
     # run: |
      #    docker compose build
       #   docker compose push
    - name: Build and Push log-monitor
      run: |
        docker build -t ghcr.io/${{ github.actor }}/log-monitor:latest -f dockerfile .
        docker push ghcr.io/${{ github.actor }}/log-monitor:latest

    - name: Build and Push log-generator
      run: |
        docker build -t ghcr.io/${{ github.actor }}/log-generator:latest -f dockerfile.generator .
        docker push ghcr.io/${{ github.actor }}/log-generator:latest
