name: Build and Push to GHCR

on:
  push:
    branches: [ Test ]  # or change to your branch
    paths :
      - '**/Dockerfile*'
      - docker-compose.yml
      - .github/workflows/docker-ghcr.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GH_TOKEN }}
    - name: Build and Push images with Compose
      run: |
          docker-compose build
          docker-compose push
